version: 2

defaults: &defaults
  docker:
    - image: docker:19.03.3
  working_directory: /template-base-image

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: &install_dependencies
          name: Install dependencies
          command: |
            # dependencies for building the image
            apk add --no-cache --no-progress make
      - run:
          name: Build Docker image
          command: |
            make image_build
      - run:
            name: List installed pip packages
            command: |
              make image_pip_list
              
  build_and_deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: *install_dependencies
      - run:
          name: Build Docker image
          command: |
            make image_build
      - run:
          name: Publish Docker Image
          command: |
            make dockerhub_login
            make image_deploy

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /v.*/
      - build_and_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
