version: 2
jobs:
  build:
    working_directory: /template-base-image
    docker:
      - image: docker:19.03-rc-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --no-cache make python3==3.7.4-r0
      - run:
          name: Build application Docker image
          command: make image
      - run:
            name: Run tests
            command: make test
      - deploy:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_NAME" -p "$DOCKERHUB_PASSWORD"
            docker push neuromation/base:latest
workflows:
  version: 2
  main:
    jobs:
      - build
