version: 2
jobs:
  build:
    working_directory: /template-base-image
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --no-cache make python3
      - run:
          name: Build application Docker image
          command: make image
      - run:
            name: Run tests
            command: make test
      - deploy:
          name: Push application Docker image
          command: make docker_push
workflows:
  version: 2
  main:
    jobs:
      - build
