version: 2

defaults: &defaults
  docker:
    - image: docker:19.03.3
  working_directory: /template-base-image

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: &install_dependencies
          name: Install dependencies
          command: |
            # dependencies for building the image
            apk add --no-cache --no-progress make
            # dependencies for testing pip dependencies (python must support typing)
            apk add --no-cache --no-progress python3 py-pip git
            # dependencies for testing ssh (grep must have -P option)
            apk add --no-cache --no-progress grep==3.3-r0 openssh-client==8.1_p1-r0
            # dependencies for testing gcloud: pip-package 'fernet' needs it
            apk add --no-cache --no-progress py-cryptography
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -U pip
            pip3 install -r testing/requirements.txt

      - run:
          name: Assert freshness of the recipes
          command: |
            source venv/bin/activate
            git diff --exit-code
            { make generate_recipes && git diff --exit-code; } || { echo -e "Need to update recipes!"; exit 3; }

      - run:
          name: Build application Docker image
          command: |
            make image_build

      - run:
            name: List installed pip packages
            command: |
              make image_pip_list
              
      - run:
            name: Prepare testing environment
            command: |
              # Since we use remote docker, in order to mount `testing/` folder to the container, we need to copy it first.
              # Source: https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
              # create a dummy container which will hold a volume with config:
              docker create -v /testing --name=aux alpine /bin/true
              # copy testing folder into this volume:
              docker cp testing/ aux:/

      - run:
            name: Run tests
            no_output_timeout: 30m
            command: |
              # Run ssh tests:
              make test_ssh  SSH_OPTION="-e EXPOSE_SSH=yes"   SSH_ENABLED=yes
              make test_ssh  SSH_OPTION="-e EXPOSE_SSH=value" SSH_ENABLED=yes
              make test_ssh  SSH_OPTION="-e EXPOSE_SSH="      SSH_ENABLED=no
              make test_ssh  SSH_OPTION='-e EXPOSE_SSH=""'    SSH_ENABLED=no
              make test_ssh  SSH_OPTION=""                    SSH_ENABLED=no
              make cleanup_test_ssh

              # Run tests on 'gcloud auth':
              make _test_gcloud_false  # should be no gsutil auth
              make _generate_gcloud_key
              docker create -v /testing --name=test-gsutil alpine /bin/true
              docker cp testing/ test-gsutil:/
              make _test_gcloud_true  IMAGE_TEST_DOCKER_MOUNT_OPTION="--volumes-from=test-gsutil"   # should succeed to auth gsutil

              # Run tests on 'wandb login':
              make test_wandb  IMAGE_TEST_DOCKER_MOUNT_OPTION="--volumes-from=aux"

              # Run tests on stdou+stderr redirect to /tmp/output:
              make test_output

              # Run tests on pip dependencies:
              make test_dependencies_pip  IMAGE_TEST_DOCKER_MOUNT_OPTION="--volumes-from=aux"

      - run:
            name: Download logs dir from the remote docker
            command: |
              docker cp aux:/testing/logs testing/

      - run:
            name: Cleanup test dirs
            command: |
              make _delete_gcloud_key || true
            when: always

      - store_artifacts:
          path: testing/logs
          when: always

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *install_dependencies
      - run:
          name: Build application Docker image
          command: |
            make image_build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            make dockerhub_login
            make image_deploy

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /v.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
