name: Continuous Integration

on:
  pull_request:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          make image_build

      - name: List installed pip packages
        run: |
          make image_pip_list

  publish:
    name: Publish image
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'release' || github.ref == 'refs/heads/master')
    env:
      DOCKER_SERVER: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: neuromation/web-shell
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: "Set up env vars: master branch"
        if: github.ref == 'refs/heads/master'
        run: |
          echo ::set-env name=TAGS::"$(date +%Y%m%d).debug-$GITHUB_RUN_NUMBER"
     
      - name: "Set up env vars: release tag"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ::set-env name=TAGS::"latest, ${GITHUB_REF#refs/tags/}"
     
      - name: Push image
        run: |
          set -x
          docker login $DOCKER_SERVER --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          
          test "$TAGS"  # assert $TAGS not empty
          for tag in $(echo $TAGS | tr "," " ")
          do
            docker push $IMAGE_NAME:$tag
          done
