name: Continuous Integration

on:
  pull_request:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  build:
    env:
      IMAGE_NAME: neuromation/base
      DOCKERFILE_PATH: Dockerfile.DEBUG
    
    name: Build, test and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Login DockerHub
        env:
          DOCKER_SERVER: docker.io
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_SERVER

      - name: Build image
        run: |
            make image_build
 
      - name: Push master
        if: github.ref == 'refs/heads/master'
        run: |
          export GIT_TAGS="master-$(date +%Y%m%d)-$GITHUB_RUN_NUMBER"
          make image_deploy

      - name: Push release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export GIT_TAGS="latest,${GITHUB_REF#refs/tags/}"
          make image_deploy
